var students = ["perycles",
		"andrepda",
		"andreson",
		"anthonini",
		"werewolf",
		"caiocesarms",
		"carine-cad",
		"ceac13",
		"diego.hdo",
		"diegomuniz",
		"dilberto",
		"lroktu",
		"duartefq",
		"tolkiendili",
		"emersonaltura",
		"ericlemos",
		"gilzitoz",
		"gabvasiljevic",
		"gabioliveira",
		"george.inf",
		"igordp",
		"isaacnewton",
		"ic3berg",
		"jandsonribeiro",
		"jeansilva",
		"joaopinto",
		"lkzfox",
		"juc",
		"titiocaju",
		"kalinegreiros",
		"leilacristina",
		"lilirisi",
		"xxduduxx",
		"lucascasoares",
		"lucas_tac",
		"marcelodl",
		"nmclemente",
		"master_pedro",
		"sonhador",
		"tadeuslima",
		"tamyreslucena",
		"tiagodantass",
		"victor2105",
		"absolutezero",
		"_vivianep",
		"wanderson.m",
		"wtts",
		"wendell.cmd",
		"leandru",
		"patrickts"];

var num_students = students.length;

var def = {
    num_exercises: 1
};